### Base URL
@baseUrl = http://localhost:8083/ecommerce/api/orders

@token = eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJ0ZXN0dXNlcjJAZ21haWwuY29tIiwicm9sZSI6IlJPTEVfVVNFUiIsImlhdCI6MTc3NjU3NjM5NCwiZXhwIjoxNzc2NjEyMzk0fQ.S8V1-DucuaMgKFViE9H8sg_Cgw1mG7oYgY4Iy8IDISs

### Create new product
POST {{baseUrl}}
Content-Type: application/json
Authorization: Bearer {{token}}

{
    "productId": 1,
    "quantity": 2
}


### Get All products
GET {{baseUrl}}
Content-Type: application/json


### Get Product by Id
GET {{baseUrl}}/4
Content-Type: application/json


