### Base URL
@baseUrl = http://localhost:8080/ecommerce/api/products

@token = eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJ0ZXN0dXNlcjFAZ21haWwuY29tIiwicm9sZSI6IlJPTEVfVVNFUiIsImlhdCI6MTc3NzQ0NTY3NCwiZXhwIjoxNzc3NDgxNjc0fQ.wOkLmL7HjiNLiKUDhOGYccX8vaiApu-8XImd6vvcUbg


### Create new product
POST {{baseUrl}}
Content-Type: application/json
Authorization: Bearer {{token}}

{
    "name": "Product1",
    "description": "Description of product 1",
    "price": 10,
    "quantity": 100
}


### Get All products
GET {{baseUrl}}
Content-Type: application/json
Authorization: Bearer {{token}}


### Get Product by Id
GET {{baseUrl}}/1
Content-Type: application/json
Authorization: Bearer {{token}}


