### Base URL
@baseUrl = http://localhost:8080/ecommerce/api/products

@token = eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJ0ZXN0dXNlcjFAZ21haWwuY29tIiwicm9sZSI6IlJPTEVfVVNFUiIsImlhdCI6MTc3NjYwMTA2NSwiZXhwIjoxNzc2NjM3MDY1fQ.7mEw7Qcq13845uabSJVElH_Sjjcbi48nm4RaJ3iVy2c


### Create new product
POST {{baseUrl}}
Content-Type: application/json
Authorization: Bearer {{token}}

{
    "name": "Product2",
    "description": "Description of product 2",
    "price": 10,
    "quantity": 100
}


### Get All products
GET {{baseUrl}}
Content-Type: application/json
Authorization: Bearer {{token}}


### Get Product by Id
GET {{baseUrl}}/1
Content-Type: application/json
Authorization: Bearer {{token}}


