### Base URL
@baseUrl = http://localhost:8082/ecommerce/api/products


### Create new product
POST {{baseUrl}}
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJ0ZXN0dXNlcjFAZ21haWwuY29tIiwicm9sZSI6IlJPTEVfVVNFUiIsImlhdCI6MTc3NjAxMDI5MiwiZXhwIjoxNzc2MDQ2MjkyfQ.C1Tl-8mqy2aEoo55sgoMpMFvvmQiS2gnZOne-uM6h_M

{
    "name": "Product2",
    "description": "Description of product 2",
    "price": 10,
    "quantity": 100
}


### Get All products
GET {{baseUrl}}
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJ0ZXN0dXNlcjFAZ21haWwuY29tIiwicm9sZSI6IlJPTEVfVVNFUiIsImlhdCI6MTc3NjAxMDI5MiwiZXhwIjoxNzc2MDQ2MjkyfQ.C1Tl-8mqy2aEoo55sgoMpMFvvmQiS2gnZOne-uM6h_M


### Get Product by Id
GET {{baseUrl}}/4
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJ0ZXN0dXNlcjFAZ21haWwuY29tIiwicm9sZSI6IlJPTEVfVVNFUiIsImlhdCI6MTc3NjAxMDI5MiwiZXhwIjoxNzc2MDQ2MjkyfQ.C1Tl-8mqy2aEoo55sgoMpMFvvmQiS2gnZOne-uM6h_M


