### Base URL
@baseUrl = http://localhost:8080/ecommerce/api/auth


### Register a new user
POST {{baseUrl}}/register
Content-Type: application/json

{
    "name": "testuser1",
    "email": "testuser1@gmail.com",
    "password": "testpassword1"
}

### User login
POST {{baseUrl}}/login
Content-Type: application/json

{
    "email": "testuser@gmail.com",
    "password": "testpassword"
}